spring.config.import=optional:file:.env[.properties], optional:classpath:metadata.properties

spring.application.name=${SPRING_APP_NAME}
spring.profiles.active=${SPRING_ENV}
eureka.client.service-url.defaultZone=${SPRING_EUREKA_URL}

management.endpoints.web.exposure.include=health,info,gateway

# Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=auth-api
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://${SERVICE_AUTH_ID}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=acounting-manager-api
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://${SERVICE_ACCOUNTING_MANAGER_ID}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/accounting-manager/**

spring.cloud.gateway.server.webmvc.routes[2].id=store-manager-api
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://${SERVICE_STORE_MANAGER_ID}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/store-manager/**

spring.cloud.gateway.server.webmvc.routes[3].id=vet-manager
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://${SERVICE_VET_MANAGER_ID}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/vet-manager/**
