# App
spring.application.name=${SPRING_APP_NAME}-dev
server.port=${HOST_PORT}
spring.log.level=${SPRING_LOG_LEVEL}

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
